### ISSUE TITLE
Can't modify frozen NilClass error

### ISSUE THREAD

**Issue by peterseverin** [felipec/soap4r#22]
I've got the following error with soap2r gem:

/home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:341:in `instance_variable_set': can't modify frozen NilClass (RuntimeError)
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:341:in `block in set_attributes'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:334:in `each'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:334:in `set_attributes'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/factory.rb:88:in `setiv2struct'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/factory.rb:35:in `setiv2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:413:in `unknownstruct2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:373:in `unknowntype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:229:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:381:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:309:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:154:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:355:in `block in anytype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/baseData.rb:620:in `each'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:353:in `anytype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:378:in `unknowntype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:229:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:381:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:309:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:154:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:355:in `block in anytype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/baseData.rb:620:in `each'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:353:in `anytype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:378:in `unknowntype2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/rubytypeFactory.rb:229:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:381:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/encodedregistry.rb:309:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:154:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/wsdlencodedregistry.rb:64:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:154:in `_soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:65:in `block in soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:559:in `block in protect_mapping'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:532:in `protect_threadvars'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:548:in `protect_mapping'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/mapping/mapping.rb:64:in `soap2obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/rpc/proxy.rb:536:in `response_rpc_enc'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/rpc/proxy.rb:519:in `response_rpc'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/rpc/proxy.rb:420:in `response_obj'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/rpc/proxy.rb:163:in `call'
	from /home/site/.rvm/gems/ruby-2.2.1@ruby22/gems/soap2r-1.5.8/lib/soap/rpc/driver.rb:151:in `call'

**Comment by tjarratt** [comment]
Closed by #23
